apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
  namespace: db-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      id: "c0909942"
  template:
    metadata:
      labels:
        id: "c0909942"
        app: db-app
        env: dev
    spec:
      containers:
      - name: db-app
        image: mariadb:10.6.4-focal
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_PASSWORD
        ports:
          - containerPort: 3306