apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-app
  namespace: nginx-proxy-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      id: "c0909942"
  template:
    metadata:
      labels:
        id: "c0909942"
        app: nginx-proxy-app
        env: dev
    spec:
      containers:
      - name: nginx-proxy-app
        image: shubham942/nginx-proxy
        ports:
          - containerPort: 80